export const projects = [
  {
    id: 1,
    name: "Ö.Y Evi",
    isveren: "Ö.Y ",
    konum: "Meram, Konya",
    olcek: "200m²",
    tarih: "2022",
    tip: "Konut",
    durum: "İç Mimari",
    ekip: "Mesva Mimarlık",
    images: [
      "/images/OY-Evi/1.jpg",
      "/images/OY-Evi/2.jpg",
      "/images/OY-Evi/3.jpg",
      "/images/OY-Evi/4.jpg",
      "/images/OY-Evi/5.jpg",
      "/images/OY-Evi/6.jpg",
      "/images/OY-Evi/7.jpg",
      "/images/OY-Evi/8.jpg",
      "/images/OY-Evi/9.jpg",
      "/images/OY-Evi/10.jpg",
      "/images/OY-Evi/11.jpg",
      "/images/OY-Evi/12.jpg",
      "/images/OY-Evi/13.jpg",
      "/images/OY-Evi/14.jpg",
      "/images/OY-Evi/15.jpg",
      "/images/OY-Evi/16.jpg",
    ],
  },
  {
    id: 2,
    name: "Gökçeada Konsept Proje",
    isveren: "Erdoğan İnşaat",
    konum: "Gökçeada, Çanakkale",
    olcek: "1200m²",
    tarih: "2022",
    tip: "Konut",
    durum: "Konsept",
    ekip: "Mesva Mimarlık",
    images: [
      "/images/gokceada/1.jpg",
      "/images/gokceada/2.jpg",
      "/images/gokceada/3.jpg",
      "/images/gokceada/4.jpg",
      "/images/gokceada/5.jpg",
      "/images/gokceada/6.jpg",
      "/images/gokceada/7.jpg",
      "/images/gokceada/8.jpg",
      "/images/gokceada/9.jpg",
      "/images/gokceada/10.jpg",
      "/images/gokceada/11.jpg",
      "/images/gokceada/12.jpg",
      "/images/gokceada/13.jpg",
      "/images/gokceada/14.jpg",
      "/images/gokceada/15.jpg",
      "/images/gokceada/16.jpg",
      "/images/gokceada/17.jpg",
      "/images/gokceada/18.jpg",
      "/images/gokceada/19.jpg",
      "/images/gokceada/20.jpg",
      "/images/gokceada/21.jpg",
    ],
  },
  {
    id: 3,
    name: "Seçer Yapı Konut Projesi",
    isveren: "Seçer Yapı",
    konum: "Gelibolu, Çanakkale",
    olcek: "1600m²",
    tarih: 2023,
    tip: "Konut",
    durum: "Konsept, Ruhsat, Uygulama",
    ekip: "Mesva Mimarlık",
    images: [
      "/images/secer-yapi-konut-projesi/1.jpg",
      "/images/secer-yapi-konut-projesi/2.jpg",
      "/images/secer-yapi-konut-projesi/3.jpg",
      "/images/secer-yapi-konut-projesi/4.jpg",
      "/images/secer-yapi-konut-projesi/5.jpg",
    ],
  },
  {
    id: 4,
    name: "İzmir Müstakil Ev",
    isveren: "Sahra Şehircilik",
    konum: "Foça, İzmir",
    olcek: "2000m²",
    tarih: 2021,
    tip: "Konut",
    durum: "Konsept",
    ekip: "Mesva Mimarlık",
    images: [
      "/images/izmir-mustakil-ev/1.jpg",
      "/images/izmir-mustakil-ev/2.jpg",
      "/images/izmir-mustakil-ev/3.jpg",
      "/images/izmir-mustakil-ev/4.jpg",
      "/images/izmir-mustakil-ev/5.jpg",
      "/images/izmir-mustakil-ev/6.jpg",
      "/images/izmir-mustakil-ev/7.jpg",
      "/images/izmir-mustakil-ev/8.jpg",
      "/images/izmir-mustakil-ev/9.jpg",
      "/images/izmir-mustakil-ev/10.jpg",
    ],
  },
  {
    id: 5,
    name: "Konya Müstakil Ev",
    isveren: "Fatih Dağ",
    konum: "Kadınhanı,Konya",
    olcek: "400m²",
    tarih: 2022,
    tip: "Konut",
    ekip: "Mesva Mimarlık",
    images: [
      "/images/konya-mustakil-ev/1.jpg",
      "/images/konya-mustakil-ev/2.jpg",
      "/images/konya-mustakil-ev/3.jpg",
      "/images/konya-mustakil-ev/4.jpg",
      "/images/konya-mustakil-ev/5.jpg",
      "/images/konya-mustakil-ev/6.jpg",
      "/images/konya-mustakil-ev/7.jpg",
      "/images/konya-mustakil-ev/8.jpg",
    ],
  },
  {
    id: 6,
    name: "Erenkoy Eğitim ve Araştırma Hastanesi",
    isveren: "Erenköy Ruh ve Sinir Hastalıkları Hastanesi",
    konum: "Erenköy, İstanbul",
    olcek: "51,500m²",
    tarih: 2021,
    tip: "Sağlık",
    durum: "Yarışma",
    ekip: "Mesva Mimarlık - Melce Mimarlık",
    images: [
      "/images/erenkoy-hastane/1.jpg",
      "/images/erenkoy-hastane/2.jpg",
      "/images/erenkoy-hastane/3.jpg",
      "/images/erenkoy-hastane/4.jpg",
      "/images/erenkoy-hastane/5.jpg",
      "/images/erenkoy-hastane/6.jpg",
      "/images/erenkoy-hastane/7.jpg",
    ],
  },
  {
    id: 7,
    name: "Konut + Ticaret Projesi",
    isveren: "Seçer Yapı",
    konum: "Gelibolu, Çanakkale",
    olcek: "1600m²",
    tarih: 2023,
    tip: "Konut + Ticaret (Karma Kullanim)",
    durum: "Konsept, Ruhsat, Uygulama",
    ekip: "Mesva Mimarlık",
    images: [
      "/images/Konut+Ticaret/1.jpg",
      "/images/Konut+Ticaret/2.jpg",
      "/images/Konut+Ticaret/3.jpg",
      "/images/Konut+Ticaret/4.jpg",
      "/images/Konut+Ticaret/5.jpg",
    ],
  },
];
