export const projects = [
  {
    id: 1,
    name: "Ö.Y EVİ",
    isveren: "Ö.Y ",
    konum: "Meram, Konya",
    olcek: "200m²",
    tarih: "2022",
    tip: "Konut",
    durum: "İç Mimari",
    ekip: "Mesva Mimarlık",
    images: [
      "/images/OY-Evi/1.jpg",
      "/images/OY-Evi/2.jpg",
      "/images/OY-Evi/3.jpg",
      "/images/OY-Evi/4.jpg",
      "/images/OY-Evi/5.jpg",
      "/images/OY-Evi/6.jpg",
      "/images/OY-Evi/7.jpg",
      "/images/OY-Evi/8.jpg",
      "/images/OY-Evi/9.jpg",
      "/images/OY-Evi/10.jpg",
      "/images/OY-Evi/11.jpg",
      "/images/OY-Evi/12.jpg",
      "/images/OY-Evi/13.jpg",
      "/images/OY-Evi/14.jpg",
      "/images/OY-Evi/15.jpg",
      "/images/OY-Evi/16.jpg",
    ],
  },
  {
    id: 2,
    name: "F.K EVİ",
    isveren: "F.K",
    konum: "Selçuklu, Konya",
    olcek: "300m²",
    tarih: "2023",
    tip: "Konut",
    durum: "İç Mimari",
    ekip: "Mesva Mimarlık",
    images: [
      "/images/konya-dergah/6.jpg",
      "/images/konya-dergah/2.jpg",
      "/images/konya-dergah/3.jpg",
      "/images/konya-dergah/4.jpg",
      "/images/konya-dergah/5.jpg",
      "/images/konya-dergah/1.jpg",
    ],
  },
  {
    id: 3,
    name: "MUSTAFA OKÇU",
    isveren: "Eskon Makine",
    konum: "Selçuklu, Konya",
    olcek: "200m²",
    tarih: "2023",
    tip: "Villa Sitesi",
    durum: "İç Mimari",
    ekip: "Mesva Mimarlık",
    images: [
      "/images/mustafa-okcu/1.jpg",
      "/images/mustafa-okcu/2.jpg",
      "/images/mustafa-okcu/3.jpg",
      "/images/mustafa-okcu/4.jpg",
      "/images/mustafa-okcu/5.jpg",
      "/images/mustafa-okcu/6.jpg",
      "/images/mustafa-okcu/7.jpg",
      "/images/mustafa-okcu/8.jpg",
      "/images/mustafa-okcu/9.jpg",
      "/images/mustafa-okcu/10.jpg",
      "/images/mustafa-okcu/11.jpg",
      "/images/mustafa-okcu/12.jpg",
      "/images/mustafa-okcu/13.jpg",
      "/images/mustafa-okcu/14.jpg",
      "/images/mustafa-okcu/15.jpg",
      "/images/mustafa-okcu/16.jpg",
      "/images/mustafa-okcu/17.jpg",
      "/images/mustafa-okcu/18.jpg",
      "/images/mustafa-okcu/19.jpg",
    ],
  },
  {
    id: 4,
    name: "DİLAY KUYUMCULUK",
    isveren: "Kadir A.",
    konum: "Beylikdüzü, İstanbul",
    olcek: "90m²",
    tarih: 2023,
    tip: "Ticari",
    durum: "İç Mimari",
    ekip: "Mesva Mimarlık",
    images: [
      "/images/beylikduzu-kuyumcu/1.jpg",
      "/images/beylikduzu-kuyumcu/2.jpg",
      "/images/beylikduzu-kuyumcu/3.jpg",
      "/images/beylikduzu-kuyumcu/4.jpg",
      "/images/beylikduzu-kuyumcu/5.jpg",
      "/images/beylikduzu-kuyumcu/6.jpg",
      "/images/beylikduzu-kuyumcu/7.jpg",
      "/images/beylikduzu-kuyumcu/8.jpg",
      "/images/beylikduzu-kuyumcu/9.jpg",
      "/images/beylikduzu-kuyumcu/10.jpg",
      "/images/beylikduzu-kuyumcu/11.jpg",
      "/images/beylikduzu-kuyumcu/12.jpg",
    ],
  },
  {
    id: 5,
    name: "İZMİR MÜSTAKİL EV",
    isveren: "Sahra Şehircilik",
    konum: "Foça, İzmir",
    olcek: "2000m²",
    tarih: 2021,
    tip: "Konut",
    durum: "Konsept",
    ekip: "Mesva Mimarlık",
    images: [
      "/images/izmir-mustakil-ev/1.jpg",
      "/images/izmir-mustakil-ev/2.jpg",
      "/images/izmir-mustakil-ev/3.jpg",
      "/images/izmir-mustakil-ev/4.jpg",
      "/images/izmir-mustakil-ev/5.jpg",
      "/images/izmir-mustakil-ev/6.jpg",
      "/images/izmir-mustakil-ev/7.jpg",
      "/images/izmir-mustakil-ev/8.jpg",
      "/images/izmir-mustakil-ev/9.jpg",
      "/images/izmir-mustakil-ev/10.jpg",
    ],
  },
  {
    id: 6,
    name: "KONYA MÜSTAKİL EV",
    isveren: "Fatih Dağ",
    konum: "Kadınhanı,Konya",
    olcek: "400m²",
    tarih: 2022,
    tip: "Konut",
    ekip: "Mesva Mimarlık",
    images: [
      "/images/konya-mustakil-ev/1.jpg",
      "/images/konya-mustakil-ev/2.jpg",
      "/images/konya-mustakil-ev/3.jpg",
      "/images/konya-mustakil-ev/4.jpg",
      "/images/konya-mustakil-ev/5.jpg",
      "/images/konya-mustakil-ev/6.jpg",
      "/images/konya-mustakil-ev/7.jpg",
      "/images/konya-mustakil-ev/8.jpg",
    ],
  },
  {
    id: 7,
    name: "ERENKÖY HASTANESİ YARIŞMA PROJESİ",
    isveren: "Erenköy Ruh ve Sinir Hastalıkları Hastanesi",
    konum: "Erenköy, İstanbul",
    olcek: "51,500m²",
    tarih: 2021,
    tip: "Sağlık",
    durum: "Yarışma",
    ekip: "Mesva Mimarlık - Melce Mimarlık",
    images: [
      "/images/erenkoy-hastane/1.jpg",
      "/images/erenkoy-hastane/2.jpg",
      "/images/erenkoy-hastane/3.jpg",
      "/images/erenkoy-hastane/4.jpg",
      "/images/erenkoy-hastane/5.jpg",
      "/images/erenkoy-hastane/6.jpg",
      "/images/erenkoy-hastane/7.jpg",
    ],
  },
  {
    id: 8,
    name: "KONUT + TİCARET PROJESİ ",
    isveren: "Seçer Yapı",
    konum: "Gelibolu, Çanakkale",
    olcek: "1600m²",
    tarih: 2023,
    tip: "Konut + Ticaret (Karma Kullanim)",
    durum: "Konsept, Ruhsat, Uygulama",
    ekip: "Mesva Mimarlık",
    images: [
      "/images/Konut+Ticaret/1.jpg",
      "/images/Konut+Ticaret/2.jpg",
      "/images/Konut+Ticaret/3.jpg",
      "/images/Konut+Ticaret/4.jpg",
      "/images/Konut+Ticaret/5.jpg",
    ],
  },
  {
    id: 9,
    name: "GÖKÇEADA KONSEPT PROJE",
    isveren: "Erdoğan İnşaat",
    konum: "Gökçeada, Çanakkale",
    olcek: "1200m²",
    tarih: "2022",
    tip: "Konut",
    durum: "Konsept",
    ekip: "Mesva Mimarlık",
    images: [
      "/images/gokceada/1.png",
      "/images/gokceada/2.png",
      "/images/gokceada/3.png",
      "/images/gokceada/4.png",
      "/images/gokceada/5.png",
      "/images/gokceada/6.png",
      "/images/gokceada/7.png",
      "/images/gokceada/8.png",
      "/images/gokceada/9.png",
      "/images/gokceada/10.png",
      "/images/gokceada/11.png",
      "/images/gokceada/12.png",
      "/images/gokceada/13.png",
      "/images/gokceada/14.png",
      "/images/gokceada/15.png",
      "/images/gokceada/16.png",
    ],
  },
  {
    id: 10,
    name: "SEÇER YAPI KONUT PROJESİ",
    isveren: "Seçer Yapı",
    konum: "Gelibolu, Çanakkale",
    olcek: "1600m²",
    tarih: 2023,
    tip: "Konut",
    durum: "Konsept, Ruhsat, Uygulama",
    ekip: "Mesva Mimarlık",
    images: [
      "/images/secer-yapi-konut-projesi/1.jpg",
      "/images/secer-yapi-konut-projesi/2.jpg",
      "/images/secer-yapi-konut-projesi/3.jpg",
      "/images/secer-yapi-konut-projesi/4.jpg",
      "/images/secer-yapi-konut-projesi/5.jpg",
    ],
  },
];
